GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWFhIiwiaWF0IjoxNzI2MTk2NzE4LCJleHAiOjE3MjYxOTY3Nzh9.OFczqI1Evlo8qJWTey9H3dRUi_bupIhM5auxEmQj-EM

###

POST http://localhost:3000/users/register
Content-Type: application/json

{
    "username": "aaa",
    "password": "123"
}

###

POST http://localhost:3000/users/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWFhIiwiaWF0IjoxNzI2MTk2NzE4fQ.10tzsdaEBDu8COHZQkQvkogW4WribxKXg9kyul-zLkw"
}


###

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username": "aaa",
    "password": "123"
}

###

DELETE http://localhost:3000/users/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWFhIiwiaWF0IjoxNzI2MTk2NzE4fQ.10tzsdaEBDu8COHZQkQvkogW4WribxKXg9kyul-zLkw"
}

###