GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWFhIiwiaWF0IjoxNzI1ODY5MzUyfQ.LDiQPYJXX3zWsbe4YAEUT3NeFR-WtY6X9H1hmdyxzV4

###

POST http://localhost:3000/users/register
Content-Type: application/json

{
    "username": "aaa",
    "password": "123"
}

###

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username": "aaa",
    "password": "123"
}